pipeline:
  identifier: Build_harness_ci_python_1686238123373
  name: Build harness-ci-python
  orgIdentifier: default
  projectIdentifier: cert01
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: mcascone/harness-ci-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
